### PR TITLE
update libskia to chrome/m95 branch, do not require python2 to build from source

### PR DESCRIPTION
**Pull request by anthrotype**
_Should_ fix https://github.com/googlefonts/gftools/issues/415

### CODE REVIEW

**Comment by anthrotype** [comment]
Note that we still won't be able to provide pre-compiled wheels for arm64 M1 macs, because Github doesn't provide hosted VMs for macOS with M1 architecture yet.
But at least we should be able to publish a _source_ distribution tarball that will no longer require python2.7 to build libskia, which I hope will fix the problems while building skia-pathops from source on M1 macs as repored by @eliheuer in https://github.com/googlefonts/gftools/issues/415. But we will only know after somebody actually tries to build using that sdist on an actual M1 machine.

**Comment by simoncozens** [comment]
> Github doesn't provide hosted VMs for macOS with M1 architecture yet.

Surely it does - that's how we were able to build them for ttfautohint?

**Comment by anthrotype** [comment]
no, we only cross compile for M1 using the x86_64 VM and macOS 11

**Comment by anthrotype** [comment]
so you're right, we should be able to _build_ them but not _test_ them

**Comment by anthrotype** [comment]
thanks for the reminder! I'll what I can do. It's always tricky when one doesn't have a local machine available to test a build but only relying on a remote CI.

**Pull request merged**
